# 文件位置：<你的 MoveIt 配置包>/config/moveit_controllers.yaml
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names: [joint_position_controller]   # ← 这里的名字必须与 ros2_control 中的控制器名一致

  joint_position_controller:
    type:  FollowJointTrajectory      # ← MoveIt 只认这类执行器来“执行轨迹”
    action_ns: follow_joint_trajectory  # ← 默认就是这个；通常不改
    default: true
    joints:
      - joint_base
      - joint_base_big_arm
      - joint_big_arm_small_arm
      - joint_small_arm_wrist
      - joint_wrist_hand
